---
fixtures:
    forge_modules:
      stdlib:
        repo: "puppetlabs/stdlib"
        ref: "4.22.0"
      apt:
        repo: "puppetlabs/apt"
        ref: "1.8.0"
      inifile:
        repo: "puppetlabs/inifile"
        ref: "2.1.0"
    repositories:
      facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
      puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      provision: 'https://github.com/puppetlabs/provision.git'
    symlinks:
        one: "#{source_dir}"
